#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run check-type
npx lint-staged

FILE="../.env"
if [ -s $FILE ]; then

export $(grep -v '^#' $FILE | tr -d ' ' | xargs)
echo "$FILE is been read"
case "${NODE_ENV,,}" in prod*) npm run build;; esac

fi

