#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run check-type
npx lint-staged

FILE="../.env"
echo "$FILE path"
if [ -s $FILE ]; then
echo "in file $FILE found and not empty"
export $(grep -v '^#' $FILE | tr -d ' ' | xargs)
echo "$FILE is been read"
case "${NODE_ENV,,}" in prod*) npm run build;; esac

fi

